extend = "common.toml"

[config]
load_script = "wget -nc https://raw.githubusercontent.com/cpg314/cargo-make-template/v0.1.0/common.toml"

[tasks.packages]
dependencies = ["cross"]
script = '''
set -euo pipefail
cp target-cross/x86_64-unknown-linux-gnu/release/libpolarhouse.so py/polarhouse.so
python -m build -w -o $PACKAGES py
tree $PACKAGES
'''
[tasks.tar]
clear = true
[tasks.nfpm]
clear = true
