extend = "common.toml"

[config]
load_script = "wget -nc https://raw.githubusercontent.com/cpg314/cargo-make-template/v0.1.0/common.toml"

[tasks.packages]
dependencies = ["cross"]
script = '''
set -euo pipefail
cp target-cross/x86_64-unknown-linux-gnu/release/libpolarhouse.so py/polarhouse.so
python -m build -w -o $PACKAGES py
tree $PACKAGES
'''

[tasks.test-py]
script = '''
set -euo pipefail

cargo build -r -p py

pushd target/release
ln -s libpolarhouse.so polarhouse.so || true
popd

if [ ! -d "venv" ]; then
    python -m virtualenv venv
    source venv/bin/activate
    pip install polars==0.20.7
else
    source venv/bin/activate
fi

export PYTHONPATH=target/release
python tests/test.py
deactivate
'''

[tasks.tar]
clear = true
[tasks.nfpm]
clear = true
